// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDR4NnQx2uVedULlKiI1_svLaoVyMUwoAw',
    appId: '1:684430554383:web:299e47f017b26ea2df7a7a',
    messagingSenderId: '684430554383',
    projectId: 'brokoli01-8887d',
    authDomain: 'brokoli01-8887d.firebaseapp.com',
    storageBucket: 'brokoli01-8887d.firebasestorage.app',
    measurementId: 'G-YN3Z3NJLKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-v4UATRiIjoeMyvu7t95zBwC2y9gWsJ0',
    appId: '1:684430554383:android:fa51045d8f73230ddf7a7a',
    messagingSenderId: '684430554383',
    projectId: 'brokoli01-8887d',
    storageBucket: 'brokoli01-8887d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZRsyvgh1eyXZdypfKHKVyS_M0Vz_-u-0',
    appId: '1:684430554383:ios:8e24b47d4410f935df7a7a',
    messagingSenderId: '684430554383',
    projectId: 'brokoli01-8887d',
    storageBucket: 'brokoli01-8887d.firebasestorage.app',
    iosBundleId: 'com.example.agriculturalRobot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZRsyvgh1eyXZdypfKHKVyS_M0Vz_-u-0',
    appId: '1:684430554383:ios:8e24b47d4410f935df7a7a',
    messagingSenderId: '684430554383',
    projectId: 'brokoli01-8887d',
    storageBucket: 'brokoli01-8887d.firebasestorage.app',
    iosBundleId: 'com.example.agriculturalRobot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDR4NnQx2uVedULlKiI1_svLaoVyMUwoAw',
    appId: '1:684430554383:web:5c56c9a97c663c5edf7a7a',
    messagingSenderId: '684430554383',
    projectId: 'brokoli01-8887d',
    authDomain: 'brokoli01-8887d.firebaseapp.com',
    storageBucket: 'brokoli01-8887d.firebasestorage.app',
    measurementId: 'G-9G79RBCW30',
  );

}